name: Create Static Site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build-Next-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and export
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run export
      - run: node ./scripts/generate-sitemap
      - run: touch ./out/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./out/